### ISSUE TITLE
help needed on compile

### ISSUE THREAD

**Issue by mikewang2016** [mercury-hpc/mercury#146]
following the instructions, I got the error message below:

 CMake Error at CMakeLists.txt:104 (message):
   Mercury requires an out of source Build.  Please create a separate binary
   directory and run CMake there.

But I do run ccmake in a separate folder "build"

**Comment by soumagne** [comment]
Hmm, make sure that you do not have any existing CMakeCache.txt file or CMakeFiles directory in the source directory and run ccmake/cmake again from your build directory. My guess is that you first ran cmake in the source directory, which created those files/directory then you probably saw the error message so tried to create a separate build directory to run cmake from there but since those files are still there, it is now conflicting with the source files.

**Comment by soumagne** [comment]
Did that fix your problem?
