### ISSUE TITLE
na_sm: 100% CPU consumption

### ISSUE THREAD

**Issue by ael-code** [mercury-hpc/mercury#228]
### Context
The bug affect the na_sm plugin. When the `HG_UTIL_HAS_SYSEPOLL_H` is defined.

### High level behavior 
I discovered the bug while using [margo](https://xgitlab.cels.anl.gov/sds/margo) with the na_sm plugin. Margo uses a progress thread that is invoking `HG_Progress` continuously with a timeout of `100`.
I noticed that after issuing the very first rpc, this progress thread was consuming 100% of the CPU.
The problem seems caused by the `epoll_wait` that always finds an event to process.

### In depth analysis
It turns out that after the very first rpc is issued the `NA_Progress` always find some work to do.
In particular the `hg_poll_wait()` function always finds an event to process.

When the first rpc is received by the server, an `NA_SM_SOCK` event with progress type `NA_SM_ADDR_INFO` is encountered in the `hg_poll_wait()` function. After the the progress function `na_sm_progress_sock()` processed it, it change the event's progress type to `NA_SM_SOCK_DONE`.

Now all the subsequent call to `hg_poll_wait()` will always find that event and they will try to process it.
Since the `NA_SM_SOCK_DONE` progress logic is not implemented, those calls will simply turns into a no-op. And they will return almost immediately HG_SUCCESS without making any actual progress.

In this scenario the `hg_core_progress_poll` function will consume 100% of the CPU trying to issue repeatedly the `hg_poll_wait()` function till it reach the given timeout.

Practically we are busy-waiting by using the `epoll_wait` function :)

### Conclusions
These are all the insights that I've manage to gather. Since I don't really know the internal logic of mercury I couldn't go further. I hope you'll find this information helpful.

**Comment by soumagne** [comment]
Thanks for the detailed report, I will investigate the issue.

**Comment by ael-code** [comment]
Which should be the life-cycle of the `NA_SM_ADDR_INFO` event? After we process it, should we remove the related fd from the `poll_set` or just clear the local notification?

**Comment by soumagne** [comment]
Hmm I had a look and I don't think there is any problem with that piece of code. What happens though is that if there is work in the queue, we will busy wait until the progress queue is drained. If there is no work to do, we just sleep in epoll_wait. You can force the sleep behavior by commenting out lines 3910 to 3918 of na_sm.c, maybe that would give you more hints about the underlying problem if there is any. The default behavior of the SM plugin though is that if there is any progress to make, we will busy wait until there is no more progress to make, so that we achieve better performance.

**Comment by ael-code** [comment]
This have not been fixed and is addressed in #229

**Comment by soumagne** [comment]
Thanks for catching that, I had set the wrong label. The other issue is open anyway.
