### ISSUE TITLE
Question: optimal buffer size and streaming

### ISSUE THREAD

**Issue by alberto-miranda** [mercury-hpc/mercury#279]
Hi,

we are using Mercury as the network layer of an HPC service that manages asynchronous RMA transfers for data staging and the question has recently risen about what the optimal way for transferring **really** large amounts of data is. For instance, we have a batch job that requires an 1TiB input file to be split and copied to compute nodes, resulting in file fragments of around 16/32GiB per node. 

What we have been doing up to now for smaller file sizes, is to `mmap()` the input files, send an RPC to the intended target piggybacking the input size and, after allocating an appropriate output buffer, request an RMA pull. Of course, for really large files, not enough memory might be available in the node for the `mmap()`, which means that we would need a sliding window plus additional RPCs to coordinate it. Would this be the best way to work with Mercury? If so, what considerations should be taken w.r.t. the window size/the number of in-flight RPCs?

**Comment by soumagne** [comment]
Right in that case it is best to use pipelining techniques. @carns may have some more insight to provide on that topic or point you to what he's been doing.
I do not really have any particular recommendation for the window size/number of in flight RPCs, that mostly depends on the system that you have and how much concurrency you can achieve. For now that is mostly determined experimentally. Of course if the window size is small you gain the advantage of low latency potentially by doing eager bulk transfers.

**Comment by alberto-miranda** [comment]
Obviously the level of concurrency and optimal window size would depend on the compute node architecture, my question (even if not stated clearly enough) was more regarding known constraints/limitations in Mercury itself. For instance, some libraries are known to work significantly better when using aligned buffers, or are known to choke beyond a certain number of concurrent requests. Are there such (known) limitations in Mercury?

Also, regarding pipelining, what exactly do you mean by that?

**Comment by soumagne** [comment]
Oh ok I misunderstood what you meant then. No there is no specific constraints or limitations, meaning you could fire off as much RPC requests as you'd want. Messages would be queued anyway if they are successfully posted by the underlying transport. We've usually been using 16 RPCs in flight as getting above that threshold did not seem to improve performance by much but you could experiment with that.
Pipelining is I believe what you meant by sliding window :) i.e., you'd use HG_Bulk_transfer() to only transfer pieces of data so that you remain within the memory limits of the node that you are transferring to. We've been doing that too, it is also useful because you reduce latency costs of large RMA transfers. So depending on the size of the data that you transfer and your ability to process the transferred pieces at the same time you can improve overall performance (instead of transferring one large chunk of data, waiting for that chunk of data to be transferred and then processing it). I don't really have any recommendation for a "window" size, that really depends on what better fits your server and use case, and it also depends on the transport that you are using.

**Comment by carns** [comment]
Hi @alberto-miranda !

FWIW I think the underlying transport and storage will be what determines concurrency and chunk size limits more so than Mercury.  Mercury generally just passes the bulk transfers to the underlying comm library once you get to that point.

Anecdotally I usually go for the smallest chunk size pipelining that will still be efficient for the network and storage target.  There aren't many targets out there that get significantly faster with transfers larger than a megabyte or a few MB.  If you go too big then you are tying up more memory per chunk and losing some degree over scheduling (i.e. you can't just pause or reduce memory consumption mid-RDMA) for diminishing returns on raw performance.

In the case of mmap (if you want to rdma straight into an mmap region) then you can also use msync over smaller regions to keep the kernel's memory usage under control if you pipeline.  If you have a lot of data to move at a high rate you probably want to start getting the device busy early in the transfer instead of waiting until Linux exhausts it's buffer cache, because then it will just oscillate back and forth between memory utilization and drive utilization instead of keeping everything busy at the same rate.

**Comment by alberto-miranda** [comment]
@carns Really interesting, thanks. The bit about `msync()` is really useful because we currently preallocate the output file with `truncate()/fallocate()` and `mmap()` it for RDMA, and we could use it to decide when to actually send "completed" pages to the device. This of course further complicates the issue of choosing the best combination of parameters for an optimal transfer rate, but I guess we'll just have to play with the parameters once implemented :)

@soumagne For the record, I was abusing a bit the "sliding window" concept to refer to the process used by our client to expose consecutive memory regions for RMA at manageable sizes. In the case of the client we cannot pipeline the RMA requests at the moment, because each client relies on an internal pool of threads to keep track of concurrent transfers (though I'm seriously considering to eliminate the pool of threads and rely on Mercury's queues and callbacks). The server itself does rely on a progress thread for Mercury, and fully adopts its asynchronous model, which means that it should benefit a lot from pipelining more fine-grained requests.
