### ISSUE TITLE
NA OFI: Mercury assumes interface name is the same as ofi domain name

### ISSUE THREAD

**Issue by sylviachanoiyee** [mercury-hpc/mercury#297]
Mercury (and/or CaRT) assumes interface name is the same as ofi domain name.

I have a node with the following topology. Output of ifconfig and fi_info follows.
Running with OFI_INTERFACE=hfi1_0 errors with ip address not found.
Running with OFI_INTERFCACE=ib1 errors with unable to open domain.
To workaround this issue, I had to rename the interface to match the domain name, setting both to hfi1_0.
Platform: centos linux 7
```
Topology
    HostBridge L#3
      PCIBridge
        PCI 8086:24f0
          Net L#3 "ib1"
          OpenFabrics L#4 "hfi1_0"
```
ifconfig (interface name is ib1)
```
ib1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 65520
        inet <ip_address here>  netmask 255.255.0.0  broadcast 172.16.255.255
```

fi_info (detects hfi1_0 as domain name)
```
provider: verbs;ofi_rxm
    fabric: IB-fabric
    domain: hfi1_0
    version: 1.0
    type: FI_EP_RDM
    protocol: FI_PROTO_RXM
```

Run with OFI_INTERFACE=hfi1_0
```bash
07/15-17:06:48.42 boro-82 CaRT[4083/4083] crt  ERR  src/cart/crt_init.c:706 crt_na_ofi_config_init() no IP addr found.
```

Run with OFI_INTERFACE=ib1
```bash
07/15-17:03:45.19 boro-82 CaRT[4044/4044] hg   ERR  # NA -- Error -- /home/schan15/gits/cart/_build.external-Linux/mercury/src/na/na_ofi.c:1672
 # na_ofi_domain_open(): No provider found for "verbs;ofi_rxm" provider on domain "ib1"
07/15-17:03:45.19 boro-82 CaRT[4044/4044] hg   ERR  # NA -- Error -- /home/schan15/gits/cart/_build.external-Linux/mercury/src/na/na_ofi.c:3271
 # na_ofi_initialize(): Could not open domain for verbs;ofi_rxm, ib1
07/15-17:03:45.19 boro-82 CaRT[4044/4044] hg   ERR  # NA -- Error -- /home/schan15/gits/cart/_build.external-Linux/mercury/src/na/na.c:380
```

**Comment by sylviachanoiyee** [comment]
Going to file this as a CaRT issue. Closing this ticket.

**Comment by sylviachanoiyee** [comment]
Working on a resolution for this in CaRT and turns out that Mercury needs to support decoupling of interface name and domain name as well.
Today, mercury supports 2 info string format in NA_Initialize_opt:
- with ip string (ofi+sockets://192.168.1.55:57153)
- with interface name (ofi+sockets://mlx5_0:57153)

However, both options still assume that interface name (which you see in ifconfig) is the same as the adapter (domain) name. The issue arises when interface_name != domain_name, e.g. interface_name=ib0, domain_name=mlx5_0

**Comment by soumagne** [comment]
@sylviachanoiyee I'm not sure I agree with that. mlx5_0 in that case is the name of your mlx IB adapter, you should not try to use that as the interface name when using ofi+sockets. Have a look at the documentation to configure IPoIB (https://docs.mellanox.com/pages/viewpage.action?pageId=12004991). The interface name that you pass in that case though should indeed correspond to the right adapter. So you would pass ib0 or ib1 depending on your config and not mlx5_0.

**Comment by soumagne** [comment]
Right that makes sense since that's how it is supposed to work.
Domain name is just an OFI "thing" that allows selection of the right device to use, it just happens that when using the verbs transport, the domain name matches the IB device name (what you get from the `ibv_devices` command) and not the interface name since again, you would not necessarily have IPoIB configured. In the case of sockets though, the domain name should not be the same, the domain name is the interface name since you do need IPs in that case, so OFI uses the interface name, i.e. ib1 if you configured IPoIB.
I don't think you should rename your interface to match the domain name, even if that does the trick :)
If we wanted to support that better in the case of verbs though, maybe we could add some code that tries to find the matching IB verbs device based on the IP that you gave since that's what the verbs domain name is, I could have a look at that.

**Comment by soumagne** [comment]
@sylviachanoiyee please give it a try when you have a chance. You can now pass something like: `ofi+verbs://mlx5_0/ib1:12345`
