### ISSUE TITLE
NA OFI: Explicitly determining domain for network device with verbs provider

### ISSUE THREAD

**Issue by jbrosenz** [mercury-hpc/mercury#349]
When configuring a Mercury connection using the verbs provider, the API currently requires the specification of a network device and domain.  How does one reliably determine the domain that is associated with a given network device?

The system command "ip a" gives a list of network devices but does not list domains or providers.  A libfabric fi_info scan correlates domains with providers, but makes no mention of network device names.  There are some fi_info records where the domain information is actually a network device (such as when the provider is "tcp").  When the provider is "verbs" the domain is never the network device name itself.  Since the issue here relates to specifying a network device name and domain when using the verbs provider, those other providers don't for this discussion.

I need to be able to tell an administrator tuples of [network device | domain] when specifying the verbs provider and do not have a solid way to do this.  The initial approach was to use the domain associated with the libfabric fi_info scan to find related siblings in the hwloc system device tree.  The sibling of the domain "mlx4_0" might be found to be "ib0".  If there were no other siblings, we could infer that "ib0" is the network device name if "ib0" shows up on the list of network devices according to system command "ip a".

This approach is sufficient if there are precisely two siblings in the device tree.  The complicating factor is that some fabric adapters support more than one network device.  The device tree will show three or more siblings, such as "ib0, ib1, mlx4_0", or "ib0, ib1, enp2s0, mlx4_0".  Given there will be one or more records from the fi_info scan associated with the domain "mlx4_0", how does one accurately determine that the related network device names for the verbs provider are "ib0" and "ib1" and not "enp2s0"?

I have observed that fi_info records associate an IP address for verbs providers.  Using the given IP address, I can match that with an IP address in the data from "ip a" and find a matching network device.  However, there is no API contract that says this is valid.  It's just an observation.  That makes it fragile and prone to faulty behavior as the API ingredients change.

Given that Mercury requires the domain and network device name when specifying the verbs provider, I am looking for a way to reliably obtain this information.

**Comment by krehm** [comment]
This problem occurs within our test cluster (HPE/Cray).   Each node has 2 sockets and 2 two-port cards.  We currently only cable one interface per card.  The domain names for the cards are mlx4_0 and mlx4_1.  Interfaces ib0 and ib1 are on mlx4_0, and interfaces ib2 and ib3 are on mlx4_1.  

Because different nodes in the cluster might connect to the switch using a different port in each card, we use udev rules to rename the active ports to names mlx40 and mlx41 so that the interface names are identical on every node even though the card ports might be different.   The interface names mlx40 and mlx41 will appear on every node; the 2 unused ports could be any of the names ib0 through ib4, different on each node.

Ideally, Joel's code would be able to determine which port in each card is the active port with an IPoIB address configured, and select that as the interface to use with that card's domain.   Not sure what to do in a situation where both ports are active and are configured for IPoIB; I'd be interested to hear others' thoughts.

**Comment by soumagne** [comment]
@krehm Hmm yes not entirely sure. Could you please post that question to https://github.com/ofiwg/libfabric/issues and link back to that issue? it would be best to get advice from the verbs maintainers on that case. Thanks.

**Comment by krehm** [comment]
Okay, will do, but first let me come at this from a different angle.

What will Mercury do if the application sets OFI_DOMAIN=mlx4_0, but un-sets OFI_INTERFACE, does not provide a value?  Only one of the two interfaces in the card is cabled, so fi_info -v only shows one interface in the domain.   If Mercury only presents the domain name to libfabric, it should get the correct/only interface, even though the app doesn't know the name of the interface.   Would that work?

That doesn't solve the case where libfabric presents two interfaces per domain, no way to identify which is which, but that can be pursued with the libfabric team.

**Comment by krehm** [comment]
Oops, DAOS returns DER_INVAL if OFI_INTERFACE is not set, we can't get to Mercury, DAOS needs the interface name in order to find the IP address via getifaddrs() to build the domain:ip-addr  info_string for Mercury NA_Initialize_opt().  That seems to imply that Mercury can't find the libfabric interface with just the domain name.  True?

**Comment by soumagne** [comment]
Mercury does not use environment variables, that's a DAOS/CART thing. I assume one thing you could also do is create separate HG classes, one for each interface. You can provide just the domain name, that would work, as long as the OFI domain matches a separate interface.

**Comment by jbrosenz** [comment]
I filed a slightly edited version of the original comment with the libfabric project: [https://github.com/ofiwg/libfabric/issues/5958](url)
