### ISSUE TITLE
initilization/lookup format for running examples with ofi+tcp

### ISSUE THREAD

**Issue by sktzwhj** [mercury-hpc/mercury#360]
**Describe the bug**
I was trying to run the built-in examples with the ofi+tcp plugin. According to https://mercury-hpc.github.io/documentation/, we should set ofi+tcp://ip:port for initialization while setting ofi+sockets://ip:port for lookups. However, it seems only setting both of them to ofi+tcp works. Do you think the documentation should be updated? Could anyone explain why we use different formats here at the very beginning? 

**To Reproduce**
Just set the formats in the example_rpc_clients.c for lookups and example_rpc_server.c for initilization. 

**Expected behavior**
Only setting both to ofi+tcp works, otherwise, both sides get stuck. 

**Platform (please complete the following information):**
 - Centos 8
 - Compiler version: gcc-8.3
 - Plugin and protocol used ofi+tcp
 -  libfabric 1.10.0

**Comment by carns** [comment]
That field in the plugin/protocol/lookup table field on that page is out of date.  Mercury uses the ofi tcp provider by default now, so the address format should be either ofi+tcp://ip:port or tcp://ip:port for most users.

You can also still use ofi+sockets:// to force use of the sockets provider rather than the tcp provider, but if you do so then you also need to initialize Mercury to use ofi+sockets at initialization time as well.  (i.e. it should be either all tcp or all sockets, the two providers are not compatible).

**Comment by soumagne** [comment]
Thanks for pointing that out, I had definitely missed that. Will update it.
