### ISSUE TITLE
typedefs for pointers are confusing and restrictive

### ISSUE THREAD

**Issue by gnuoyd** [mercury-hpc/mercury#411]
**The problem**
`na_addr_t` and `na_mem_handle_t` are both pointer types, which is a bit confusing when, for example, you have a function like `NA_Mem_handle_create(..., na_mem_handle_t *mem_handle)`. On the surface, it looks like `mem_handle` is a pointer to a handle that's already been allocated for me. Actually, it's a pointer to a pointer to nothing; I need to `malloc(3)` a `struct na_mem_handle` and store a pointer to it at `mem_handle`.

If `na_mem_handle_t` was a typedef for `struct na_mem_handle`, then we'd have a strong "pointer to a pointer" indication in the function declaration, `NA_Mem_handle_create(..., na_mem_handle_t **mem_handle)`. This is a common C idiom with a strong visual signal in the double asterisk, `**`.

Another downside of `_t` typedefs for pointers is its inflexibility. To add some type qualifications, you cannot use the typedef. C lets us differentiate between an immutable *reference* and an immutable *referent*, `struct na_mem_handle * const ptr` versus `const struct na_mem_handle *ptr`, with our placement of `const` qualifier. Under the current definition of `na_mem_handle_t`, however, `const na_mem_handle_t ptr` and `na_mem_handle_t const ptr` mean the same thing.

Similar considerations apply for `na_addr_t`—and possibly other types, I haven't made an exhaustive list.

**Preferred solution**
Change all instances of `typedef ... *xyz_t` to `typedef ... xyz_t` and all uses of `xyz_t` to `xyz_t *`.

**Comment by soumagne** [comment]
ok will take a look. Yeah I had moved some types to no longer be pointer types but definitely not all. I think you're right and it's probably better to be consistent with other types too. I can look at making those changes at the NA layer first.

**Comment by mdorier** [comment]
Ouch, this API change blew up MoNA big time...

**Comment by soumagne** [comment]
Yeah I do realize that, you should be able to just do a find replace of `na_addr_t` to `na_addr_t *` and `na_mem_handle_t` to `na_mem_handle_t *`...

**Comment by mdorier** [comment]
Yes, the more annoying thing is basically a large `#ifdef` block with an essentially different API depending on the version of Mercury in use. Since MoNA is public-facing and exposes the NA API as public as well, the API change propagates to users of MoNA as well.

**Comment by soumagne** [comment]
OK. I would not expect this type of significant changes to occur again in the future and I've tried to be making all the breaking API changes at the same time to minimize this type of issues... but otherwise maybe the safest solution would be to use your own type that maps to the NA types ? and same for APIs, you could have your own inline MoNA APIs that just call directly into NA even if they don't anything beside calling NA_XXX. It might be the safest thing to do in the future. Right now by having MoNA at the same level of NA basically, that exposes it to any NA API changes. Just something to think about. Agree that either way will be an API breakage though...
