### ISSUE TITLE
segfault in na/na_ofi.c

### ISSUE THREAD

**Issue by otatebe** [mercury-hpc/mercury#561]
**Describe the bug**
segfault happens in na/na_ofi.c

**Screenshots**
```
segfault at 40 ip 00007f2d2e06ec18 sp 00007f2d25b1c9c0 error 4 in libna.so.2.1.0[7f2d2e05f000+20000]

$ printf "%x\n" $((0x7f2d2e06ec18-0x7f2d2e05f000))
fc18
$ addr2line -e /.../spack/opt/spack/linux-rhel7-skylake_avx512/gcc-8.3.1/mercury-2.1.0-fqnkq4kk4k2gn433suxvzo3ldpluztzq/lib/libna.so.2 -fCi 0xfc18
hg_atomic_get32
/.../spack-stage/spack-stage-mercury-2.1.0-fqnkq4kk4k2gn433suxvzo3ldpluztzq/spack-src/src/util/mercury_atomic.h:305
na_ofi_cq_process_event
/.../spack-stage/spack-stage-mercury-2.1.0-fqnkq4kk4k2gn433suxvzo3ldpluztzq/spack-src/src/na/na_ofi.c:3336
na_ofi_progress
/.../spack-stage/spack-stage-mercury-2.1.0-fqnkq4kk4k2gn433suxvzo3ldpluztzq/spack-src/src/na/na_ofi.c:5214
```

https://github.com/mercury-hpc/mercury/blob/v2.1.0/src/util/mercury_atomic.h#L305
https://github.com/mercury-hpc/mercury/blob/v2.1.0/src/na/na_ofi.c#L3336
https://github.com/mercury-hpc/mercury/blob/v2.1.0/src/na/na_ofi.c#L5214

**Platform (please complete the following information):**
 - CentOS 7.9
 - gcc 8.3.1
 - ofi+verbs
 - libfabric 1.14.0
 - mochi-margo 0.9.8

**Comment by carns** [comment]
Hi @otatebe , what version of OFED (or MOFED or rdma-core) are you using to provide the verbs libraries underneath libfabric?

We talked about your issue during a Mercury developer call today.  The symptom you describe sounds similar to what the DAOS team encountered due to a bad interaction between recent versions of MOFED and libfabric (see https://github.com/ofiwg/libfabric/issues/7359 and https://github.com/ofiwg/libfabric/pull/7365).  If it is the same problem, then the fix has been merged in the libfabric repo, but it is not in a tagged release yet.

I think libfabric has a new release on the way soon.  Can you try either their origin/main or something newer than 1.14.0 (when available) to see if that improves matters?

**Comment by otatebe** [comment]
Hi @carns , actually this happens after we upgrade MLNX OFED from 5.1-2.5.8 to 5.5-1.0.3.2.  When I use libfabric@main, it works!  Thanks.

**Comment by carns** [comment]
Fantastic, thank you for confirming @otatebe .
