### ISSUE TITLE
Query on how to load balance connections

### ISSUE THREAD

**Issue by missiongoogle** [mercury-hpc/mercury#576]
Hello, we are running mercury within a multi-threaded server/client application.  
The client is expected to initiate a connection from each thread of its application.
On the target side, mercury is listening on one of the cores of the server application.  
Is there any way to distribute the incoming connections to different cores on the server side from the mercury target?

Off-Topic: Does Mercury release performance numbers for bulk and normal RPC use case with different IO sizes? If not, what is the expected range of latency?

**Comment by soumagne** [comment]
Not really, the only way would be to use OFI's scalable endpoints. It's not fully supported still because only a few providers support it (verbs does not support it for example). It's been in my plan to change the addressing API to better support those scenarios and still give you the ability to address a specific HG context, assuming you'd then have one context per thread. Currently though the only way would be instead to create separate classes, which would result in separate endpoints and have you address each of those endpoints separately for each thread.

You can look at some numbers there that were taken with OFI, it should still be more or less the same: https://mercury-hpc.github.io/user/ofi/ let us know if you need anything else.

**Comment by missiongoogle** [comment]
Can you please tell is the scalable endpoint implementation in verbs plugin absent at mercury's end or libfabrics itself does not have support for it as of now?
If prior, then do we have timelines as to when this can be integrated within mercury?

**Comment by carns** [comment]
It's the latter, unfortunately.  See https://github.com/ofiwg/libfabric/blob/main/man/fi_verbs.7.md under "Other unsupported features".

Some other alternatives (just to fill out your options) are to have one thread drive Mercury progress, but launch rpc handler threads in particular places to hand out the actual servicing work to other cores.  This is higher latency than going straight to the core you want, but it works fine (and this is what the Margo library does).  Yet another option is to actually run a separate process and endpoint per core, or at least per NUMA domain, and have the client treat them as separate hosts.  This is more resource intensive, though, and you have to manage more addresses.

**Comment by missiongoogle** [comment]
> It's the latter, unfortunately. See https://github.com/ofiwg/libfabric/blob/main/man/fi_verbs.7.md under "Other unsupported features".
> 
> Some other alternatives (just to fill out your options) are to have one thread drive Mercury progress, but launch rpc handler threads in particular places to hand out the actual servicing work to other cores. This is higher latency than going straight to the core you want, but it works fine (and this is what the Margo library does). Yet another option is to actually run a separate process and endpoint per core, or at least per NUMA domain, and have the client treat them as separate hosts. This is more resource intensive, though, and you have to manage more addresses.


The first alternative suggested will only create parallel processing at the server end. But the client will still be connected via a single connection only. 
The second one is not an option as that will be a management overhead for us.
What we really wanted was to listen per core and distribute the incoming connections to different cores, such that the completions of each connection are polled by the individual core itself.
Looks like we will have to wait for this.
Thanks for the suggestions.
