### ISSUE TITLE
 client send message sequence is out of order?

### ISSUE THREAD

**Issue by jin-zhengnan** [mercury-hpc/mercury#661]
i did the  test case in example_rpc_client and found it  was abnormal,  the first call helloworld is send at last, who can tell me the reason?  

the print result in server is below:

./hg_example_rpc_server verbs
svr address string: "ofi+verbs;ofi_rxm://192.168.1.108:53128"
Got RPC request with input_val: 1
Got RPC request with input_val: 2
Got RPC request with input_val: 3
Got RPC request with input_val: 0
my_rpc_handler_bulk_cb: Hello world! +1 
my_rpc_handler_bulk_cb: Hello world! +2 
my_rpc_handler_bulk_cb: Hello world! +3 
my_rpc_handler_bulk_cb: Hello world! +0 
Got RPC request with input_val: 1
Got RPC request with input_val: 2
Got RPC request with input_val: 3
Got RPC request with input_val: 0
my_rpc_handler_bulk_cb: Hello world! +1 
my_rpc_handler_bulk_cb: Hello world! +2 
my_rpc_handler_bulk_cb: Hello world! +3 
my_rpc_handler_bulk_cb: Hello world! +0 

the print result in client is below:
 ./hg_example_rpc_client verbs ofi+verbs://192.168.1.108:52200
start 
Got response ret: 0, from 1
Got response ret: 0, from 2
Got response ret: 0, from 3
Got response ret: 0, from 0
 ./hg_example_rpc_client verbs ofi+verbs://192.168.1.108:61323
start 
Got response ret: 0, from 1
Got response ret: 0, from 2
Got response ret: 0, from 3
Got response ret: 0, from 0
 ./hg_example_rpc_client verbs ofi+verbs://192.168.1.108:61323
start 
Got response ret: 0, from 0
Got response ret: 0, from 1
Got response ret: 0, from 3
Got response ret: 0, from 2

**Comment by soumagne** [comment]
RPCs are sent in order but there is no guarantee that they'll be received in the same order unless we wait for each RPC to complete before sending the next one etc, which is not what this example is doing, it's sending all RPCs in order but then waits for all completions at the same time by calling `HG_Progress()`. In general, there are multiple reasons why this could happen but in this particular case, I would assume the first RPC hit a `EAGAIN` because of the libfabric connection manager and was retried internally while the others went through.

**Comment by jin-zhengnan** [comment]
@soumagne  thanks  maybe the libfabric is poor compatibility，we use ucx no this problom，thanks  close this issue
